### ISSUE TITLE
Re-signing all the time and other issues

### ISSUE THREAD

**Issue by 5ixfeetunder** [Matchstic/Extender-Installer#21]
Thanks for this tweak. I have tried it for a few days now. Since installing this, I have encountered a few issues and I would like to report these issues:

1) Your Apple ID or password is incorrectly entered. I have signed in with the correct ID and password. My id does have an underscore.
2) The app has re-signed 6 times today and yesterday another 6 times, and 4 times the day before.
3) And today I encountered this error:
failed to resign: 'yalu102' with error: failed to verify codesignature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp/extracted/Payload/yalu102.app: 0xe8008017 (A signed resource has been added, modified or deleted)

What can be done for these issues? Thanks

**Comment by Matchstic** [comment]
The first two issues have been resolved for the coming update, and the last currently occurs at random; my assumption is that something didn't quite go correctly when Cydia Extender itself re-packaged the signed application.

**Comment by 5ixfeetunder** [comment]
Thank you for your reply. Have downloaded the 0.3.2.

**Comment by Matchstic** [comment]
Can you confirm that these issues are fixed or not please?

**Comment by Kharlyt** [comment]
Hello,
Thank you for your amazing app. 
I am using 0.3.3 and still have the first two issues. 
Is it going to be solved in the next version ?
